services:

  db:
    image: postgres:latest
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb

    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: movies

    ports:
      - 5432:5432
